### ISSUE TITLE
Issues with docker-env not found

### ISSUE THREAD

**Issue by sheetaljoshi** [adglkh/dockerized-app-snap#1]
I get 
cannot perform operation: mount --bind -o ro,nosuid,nodev /snap/docker/155 /snap/docker-app/x1/docker-env: No such file or directory

All the interfaces shows connected ok. 
root@snappy:~/dockerized-app-snap# snap interfaces | grep docker
:docker-support            docker:privileged,docker:support,docker-app:privileged,docker-app:support
:firewall-control          docker
:home                      docker
:network                   docker,docker-app
:network-bind              docker
docker:docker-daemon       docker:docker-cli,docker-app:docker-cli
docker:docker-executables  docker-app

And root@snappy:~/dockerized-app-snap# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

and snap version is 
root@snappy:~/dockerized-app-snap# snap version
snap    2.27.6
snapd   2.27.6
series  16
ubuntu  16.04
kernel  4.4.0-92-generic

core and docker snap versions as below

Name        Version       Rev   Developer   Notes
core        16-2.27.6     2898  canonical   core
docker      17.06.0-ce-1  155   docker-inc  -
docker-app  0.1           x1                -

Please advice

**Comment by adglkh** [comment]
The issue here is that docker-env folder is not found, which causes a bind mount creation failed. 
I have docker-env folder in place locally. But adding an empty directory is not allowed by Git.
https://git.wiki.kernel.org/index.php/GitFaq#Can_I_add_empty_directories.3F
I fixed with `scriptlets`
https://insights.ubuntu.com/2017/02/02/run-scripts-during-snapcraft-builds-with-scriptlets/
Please take a look. https://github.com/adglkh/dockerized-app-snap/pull/2
Could you help review it?
Thanks for your feedback.
